const chartThemes = {
    "defaultTheme": {
        gradientStart: "#0F2027",
        gradientEnd: "#2C5364",
        circleLine: "maroon",
        barLine: "gray",
        text: "#ffaaaa",
        polyline: "#a79c8e",
        chartLine: "gray",
        sleep: "#eb9f9f",
        waka: "#f1bbba",
        fit: "#f8ecc9",
    },
    "forest": {
        gradientStart: "#5a9367",
        gradientEnd: "#44633f",
        circleLine: "maroon",
        barLine: "gray",
        text: "#49010f",
        polyline: "#534847",
        chartLine: "gray",
        sleep: "#9b8281",
        waka: "#d09e88",
        fit: "#fadad8",
    },
    "blue": {
        gradientStart: "#F8F9FC",
        gradientEnd: "#A5BECF",
        circleLine: "#020715",
        barLine: "gray",
        text: "#335495",
        polyline: "#545051",
        chartLine: "gray",
        sleep: "#5B67A2",
        waka: "#7B86AA",
        fit: "#BFC8EA",
    },
    "darkforest": {
        gradientStart: "#0F2027",
        gradientEnd: "#2C5364",
        circleLine: "maroon",
        barLine: "gray",
        text: "#cff0da",
        polyline: "#3b8686",
        chartLine: "gray",
        sleep: "#79bd9a",
        waka: "#a8dba8",
        fit: "#cff09e",
    },
    "cherry": {
        gradientStart: "#87314e",
        gradientEnd: "#df405a",
        circleLine: "maroon",
        barLine: "gray",
        text: "#cff0da",
        polyline: "#1e2022",
        chartLine: "gray",
        sleep: "#52616a",
        waka: "#c9d6de",
        fit: "#f0f5f9",
    },
    "night": {
        gradientStart: "#150e56",
        gradientEnd: "#325288",
        circleLine: "maroon",
        barLine: "gray",
        text: "#fbd14b",
        polyline: "#fc913a",
        chartLine: "gray",
        sleep: "#f8ca00",
        waka: "#ede574",
        fit: "#fff1b9",
    },
};

module.exports = chartThemes;